
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:15 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:15 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/cygwin64/bin/c++.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.exe"
      
      The CXX compiler identification is GNU, found in:
        C:/Users/addyg/Downloads/Software Engineering/main-project-snoopy-corp/_build/CMakeFiles/3.31.0-rc1/CompilerIdCXX/a.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:15 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/addyg/Downloads/Software Engineering/main-project-snoopy-corp/_build/CMakeFiles/CMakeScratch/TryCompile-kjz0q1"
      binary: "C:/Users/addyg/Downloads/Software Engineering/main-project-snoopy-corp/_build/CMakeFiles/CMakeScratch/TryCompile-kjz0q1"
    cmakeVariables:
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/addyg/Downloads/Software Engineering/main-project-snoopy-corp/_build/CMakeFiles/CMakeScratch/TryCompile-kjz0q1'
        
        Run Build Command(s): "C:/Program Files/CMake/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~2/GnuWin32/bin/make.exe -f Makefile cmTC_5cc45/fast
        C:/PROGRA~2/GnuWin32/bin/make.exe  -f CMakeFiles/cmTC_5cc45.dir/build.make CMakeFiles/cmTC_5cc45.dir/build
        make.exe[1]: Entering directory `C:/Users/addyg/Downloads/Software Engineering/main-project-snoopy-corp/_build/CMakeFiles/CMakeScratch/TryCompile-kjz0q1'
        Building CXX object CMakeFiles/cmTC_5cc45.dir/CMakeCXXCompilerABI.cpp.obj
        /C/cygwin64/bin/c++.exe   -std=gnu++17   -v -o CMakeFiles/cmTC_5cc45.dir/CMakeCXXCompilerABI.cpp.obj -c "/C/Program Files/CMake/share/cmake-3.31/Modules/CMakeCXXCompilerABI.cpp"
        Using built-in specs.
        COLLECT_GCC=/usr/bin/c++
        Target: x86_64-pc-cygwin
        Configured with: /mnt/share/cygpkgs/gcc/gcc.x86_64/src/gcc-11.4.0/configure --srcdir=/mnt/share/cygpkgs/gcc/gcc.x86_64/src/gcc-11.4.0 --prefix=/usr --exec-prefix=/usr --localstatedir=/var --sysconfdir=/etc --docdir=/usr/share/doc/gcc --htmldir=/usr/share/doc/gcc/html -C --build=x86_64-pc-cygwin --host=x86_64-pc-cygwin --target=x86_64-pc-cygwin --without-libiconv-prefix --without-libintl-prefix --libexecdir=/usr/lib --with-gcc-major-version-only --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --enable-bootstrap --enable-__cxa_atexit --with-dwarf2 --with-tune=generic --enable-languages=ada,c,c++,d,fortran,lto,objc,obj-c++,jit --enable-graphite --enable-threads=posix --enable-libatomic --enable-libgomp --enable-libquadmath --enable-libquadmath-support --disable-libssp --enable-libada --disable-symvers --disable-multilib --with-gnu-ld --with-gnu-as --with-cloog-include=/usr/include/cloog-isl --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible --enable-libstdcxx-filesystem-ts
        Thread model: posix
        Supported LTO compression algorithms: zlib zstd
        gcc version 11.4.0 (GCC) 
        COLLECT_GCC_OPTIONS='-std=gnu++17' '-v' '-o' 'CMakeFiles/cmTC_5cc45.dir/CMakeCXXCompilerABI.cpp.obj' '-c' '-shared-libgcc' '-mtune=generic' '-march=x86-64' '-dumpdir' 'CMakeFiles/cmTC_5cc45.dir/'
         /usr/lib/gcc/x86_64-pc-cygwin/11/cc1plus.exe -quiet -v -idirafter /usr/lib/gcc/x86_64-pc-cygwin/11/../../../../lib/../include/w32api -idirafter /usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/lib/../lib/../../include/w32api C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeCXXCompilerABI.cpp -quiet -dumpdir CMakeFiles/cmTC_5cc45.dir/ -dumpbase CMakeCXXCompilerABI.cpp.cpp -dumpbase-ext .cpp -mtune=generic -march=x86-64 -std=gnu++17 -version -o /cygdrive/c/Users/addyg/AppData/Local/Temp/cc4I1qTC.s
        GNU C++17 (GCC) version 11.4.0 (x86_64-pc-cygwin)
        	compiled by GNU C version 11.4.0, GMP version 6.2.1, MPFR version 4.2.0-p9, MPC version 1.3.1, isl version isl-0.26-GMP
        
        warning: GMP header version 6.2.1 differs from library version 6.3.0.
        warning: MPFR header version 4.2.0-p9 differs from library version 4.2.1.
        GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
        ignoring nonexistent directory "/usr/local/include"
        ignoring nonexistent directory "/usr/lib/gcc/x86_64-pc-cygwin/11/include-fixed"
        ignoring nonexistent directory "/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/include"
        ignoring duplicate directory "/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/lib/../lib/../../include/w32api"
        #include "..." search starts here:
        #include <...> search starts here:
         /usr/lib/gcc/x86_64-pc-cygwin/11/include/c++
         /usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/x86_64-pc-cygwin
         /usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/backward
         /usr/lib/gcc/x86_64-pc-cygwin/11/include
         /usr/include
         /usr/lib/gcc/x86_64-pc-cygwin/11/../../../../lib/../include/w32api
        End of search list.
        GNU C++17 (GCC) version 11.4.0 (x86_64-pc-cygwin)
        	compiled by GNU C version 11.4.0, GMP version 6.2.1, MPFR version 4.2.0-p9, MPC version 1.3.1, isl version isl-0.26-GMP
        
        warning: GMP header version 6.2.1 differs from library version 6.3.0.
        warning: MPFR header version 4.2.0-p9 differs from library version 4.2.1.
        GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
        Compiler executable checksum: 9541cf208b0d7c1554936d7d6d06e10f
        COLLECT_GCC_OPTIONS='-std=gnu++17' '-v' '-o' 'CMakeFiles/cmTC_5cc45.dir/CMakeCXXCompilerABI.cpp.obj' '-c' '-shared-libgcc' '-mtune=generic' '-march=x86-64' '-dumpdir' 'CMakeFiles/cmTC_5cc45.dir/'
         /usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/as.exe -v -o CMakeFiles/cmTC_5cc45.dir/CMakeCXXCompilerABI.cpp.obj /cygdrive/c/Users/addyg/AppData/Local/Temp/cc4I1qTC.s
        GNU assembler version 2.42 (x86_64-pc-cygwin) using BFD version (GNU Binutils) 2.42
        COMPILER_PATH=/usr/lib/gcc/x86_64-pc-cygwin/11/:/usr/lib/gcc/x86_64-pc-cygwin/11/:/usr/lib/gcc/x86_64-pc-cygwin/:/usr/lib/gcc/x86_64-pc-cygwin/11/:/usr/lib/gcc/x86_64-pc-cygwin/:/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/
        LIBRARY_PATH=/usr/lib/gcc/x86_64-pc-cygwin/11/:/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/lib/../lib/:/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../lib/:/lib/../lib/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/lib/:/usr/lib/gcc/x86_64-pc-cygwin/11/../../../:/lib/:/usr/lib/
        COLLECT_GCC_OPTIONS='-std=gnu++17' '-v' '-o' 'CMakeFiles/cmTC_5cc45.dir/CMakeCXXCompilerABI.cpp.obj' '-c' '-shared-libgcc' '-mtune=generic' '-march=x86-64' '-dumpdir' 'CMakeFiles/cmTC_5cc45.dir/CMakeCXXCompilerABI.cpp.'
        Linking CXX executable cmTC_5cc45.exe
        "/C/Program Files/CMake/bin/cmake.exe" -E rm -f CMakeFiles/cmTC_5cc45.dir/objects.a
        /C/cygwin64/bin/ar.exe qc CMakeFiles/cmTC_5cc45.dir/objects.a @CMakeFiles/cmTC_5cc45.dir/objects1.rsp
        process_begin: CreateProcess(NULL, /C/cygwin64/bin/ar.exe qc CMakeFiles/cmTC_5cc45.dir/objects.a @CMakeFiles/cmTC_5cc45.dir/objects1.rsp, ...) failed.
        make (e=2): The system cannot find the file specified.\x0d
        make.exe[1]: *** [cmTC_5cc45.exe] Error 2
        make.exe[1]: Leaving directory `C:/Users/addyg/Downloads/Software Engineering/main-project-snoopy-corp/_build/CMakeFiles/CMakeScratch/TryCompile-kjz0q1'
        make.exe: *** [cmTC_5cc45/fast] Error 2
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeTestCXXCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:15 (project)"
    checks:
      - "Check for working CXX compiler: C:/cygwin64/bin/c++.exe"
    directories:
      source: "C:/Users/addyg/Downloads/Software Engineering/main-project-snoopy-corp/_build/CMakeFiles/CMakeScratch/TryCompile-ubdz22"
      binary: "C:/Users/addyg/Downloads/Software Engineering/main-project-snoopy-corp/_build/CMakeFiles/CMakeScratch/TryCompile-ubdz22"
    cmakeVariables:
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_CXX_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/addyg/Downloads/Software Engineering/main-project-snoopy-corp/_build/CMakeFiles/CMakeScratch/TryCompile-ubdz22'
        
        Run Build Command(s): "C:/Program Files/CMake/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~2/GnuWin32/bin/make.exe -f Makefile cmTC_8fb4e/fast
        C:/PROGRA~2/GnuWin32/bin/make.exe  -f CMakeFiles/cmTC_8fb4e.dir/build.make CMakeFiles/cmTC_8fb4e.dir/build
        make.exe[1]: Entering directory `C:/Users/addyg/Downloads/Software Engineering/main-project-snoopy-corp/_build/CMakeFiles/CMakeScratch/TryCompile-ubdz22'
        Building CXX object CMakeFiles/cmTC_8fb4e.dir/testCXXCompiler.cxx.obj
        /C/cygwin64/bin/c++.exe   -std=gnu++17 -o CMakeFiles/cmTC_8fb4e.dir/testCXXCompiler.cxx.obj -c "/C/Users/addyg/Downloads/Software Engineering/main-project-snoopy-corp/_build/CMakeFiles/CMakeScratch/TryCompile-ubdz22/testCXXCompiler.cxx"
        Linking CXX executable cmTC_8fb4e.exe
        "/C/Program Files/CMake/bin/cmake.exe" -E rm -f CMakeFiles/cmTC_8fb4e.dir/objects.a
        /C/cygwin64/bin/ar.exe qc CMakeFiles/cmTC_8fb4e.dir/objects.a @CMakeFiles/cmTC_8fb4e.dir/objects1.rsp
        process_begin: CreateProcess(NULL, /C/cygwin64/bin/ar.exe qc CMakeFiles/cmTC_8fb4e.dir/objects.a @CMakeFiles/cmTC_8fb4e.dir/objects1.rsp, ...) failed.
        make (e=2): The system cannot find the file specified.\x0d
        make.exe[1]: *** [cmTC_8fb4e.exe] Error 2
        make.exe[1]: Leaving directory `C:/Users/addyg/Downloads/Software Engineering/main-project-snoopy-corp/_build/CMakeFiles/CMakeScratch/TryCompile-ubdz22'
        make.exe: *** [cmTC_8fb4e/fast] Error 2
        
      exitCode: 2
...
